CREATE TABLE "USERS" (
  "LOGIN_ID" NUMBER(10,0) NOT NULL ENABLE, 	
	"NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE, 	
	CONSTRAINT "USER_PK" PRIMARY KEY ("LOGIN_ID")
);


CREATE OR REPLACE TRIGGER USER_TRG
BEFORE INSERT OR UPDATE ON "USERS" 
  FOR EACH ROW
  BEGIN  
    :NEW.login_id := UPPER(:NEW.login_id);
  END;
/

ALTER TRIGGER USER_TRG ENABLE;
